# To use:
# brew install pre-commit gawk terraform-docs tflint coreutils
repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args: ['--envs=AWS_DEFAULT_REGION="us-west-2"']
      - id: terraform_docs
